# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add connector lifecycle metadata.

Revision ID: f670d1ed8681
Revises: 6ea9c44bb683
Create Date: 2026-09-21 09:09:03.187252
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from flwr.supercore.state.schema.types import UTCDateTime

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "f670d1ed8681"
down_revision: str | Sequence[str] | None = "6ea9c44bb683"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NAMING_CONVENTION = {
    "pk": "pk_%(table_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s_%(column_1_name)s",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "connector",
        schema=None,
        naming_convention=NAMING_CONVENTION,
        recreate="always",
    ) as batch_op:
        batch_op.add_column(
            sa.Column("connector_id", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.add_column(sa.Column("federation_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("created_at", UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column("deleted_at", UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column("created_by", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("deleted_by", sa.String(), nullable=True))
        batch_op.drop_constraint("pk_connector", type_="primary")
        batch_op.create_primary_key("pk_connector", ["connector_id"])
        batch_op.create_unique_constraint(
            "uq_connector_flwr_aid_connector_ref", ["flwr_aid", "connector_ref"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "connector",
        schema=None,
        naming_convention=NAMING_CONVENTION,
        recreate="always",
    ) as batch_op:
        batch_op.drop_constraint("uq_connector_flwr_aid_connector_ref", type_="unique")
        batch_op.drop_constraint("pk_connector", type_="primary")
        batch_op.create_primary_key("pk_connector", ["flwr_aid", "connector_ref"])
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("federation_id")
        batch_op.drop_column("connector_id")

    # ### end Alembic commands ###
